stages:
    - test
    - build

build_win:
    stage: build
    before_script:
        - cd genx
    script:
        - 'C:\Users\glavic_a\AppData\Local\Continuum\anaconda3\scripts\conda run pyinstaller genx.spec'
        - 'iscc windows_build\genx.iss'
        - 'move windows_build\Output\*.* d:\GitLab-Runner\dist\'
    tags:
        - windows
    only:
        - tags

build_ubuntu_lts:
    image: linux_genx
    stage: build
    before_script:
        - cd genx
    script:
        - python3 setup.py bdist
        - bash debian_build/make_deb.sh
        - ls dist
        - mv dist/*.deb /data/dist/
    tags:
        - docker
    only: 
        - tags
    
build_ubuntu_eoan:
    image: eoan_genx
    stage: build
    before_script:
        - cd genx
    script:
        - python3 setup.py bdist
        - bash debian_build/make_deb.sh
        - ls dist
        - mv dist/*.deb /data/dist/
    tags:
        - docker
    only:
        - tags
    
