name: genx
adopt-info: genx
summary: GenX 3 - Reflectometry and surface diffraction refinement
description: |
  GenX is a versatile program using the differential evolution algorithm for fitting, primarily, X-ray and neutron reflectivity data, 
  lately also surface x-ray diffraction data. The differential evolution algorithm is a robust optimization method which avoids local minima 
  but at same is a highly effective. GenX is written in python and uses the wxpython package for the Graphical User Interface (GUI) Screenshot. 
  A model to fit is defined either through a GUI plug-in or via a python script. The possibility to script everything makes it easy to develop completely new fitting model. 
  Clearly, GenX is extremely modular, making it possible to extend the program with models and plug-ins for most fitting problems. 
  
  At the present GenX is shipped with models for x-ray and neutron specular reflectivity, off-specular x-ray reflectivity and surface x-ray diffraction. 
  A detailed description, of a older version, has been published in https://www.iucr.org/cgi-bin/paper?aj5091 .
  
  Feedback and Help:
  You can find a manual with examples at https://aglavic.github.io/genx/doc/, for reflectometry a good start is with the SimpleReflectivity guide
  https://aglavic.github.io/genx/doc/tutorials/simple_reflectivity.html and our Tutorial Videos
  https://aglavic.github.io/genx/doc/tutorials/neutron_fit.html.
  
  Naturally a program does not become better if I do not get feedback from you! 
  If you found a bug or want to have something included in the program submit a ticket on SourceForge at https://sourceforge.net/p/genx/tickets/ .
base: core22
confinement: strict
grade: stable

architectures: 
  - build-on: amd64

parts:
  genx:
    plugin: python
    source: ./genx
    python-packages:
      - wheel
      - numpy
      - bumps
      - vtk
      - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.1-cp310-cp310-linux_x86_64.whl
      - svgwrite
    #build-packages:
      #- python3-pip
      #- python3-wheel
    stage-packages:
      - libsdl2-2.0-0
      - libegl1
      - libxtst6
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libjavascriptcoregtk-4.0-18
      - libwebkit2gtk-4.0-37
      - libpsm2-2-compat
      - libgomp1-amd64-cross
      - libsm6
      - libtbb2
      - libpulsecommon-15.99
    after: [desktop-gnome-platform]
    override-pull: |
      snapcraftctl pull
      mkdir repo
      cd repo
      git clone --bare https://github.com/aglavic/genx.git .
      snapcraftctl set-version $(git describe --tags)
      cd ..
      rm -rf repo 
 
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - gcc
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

#  snapcraft-preload:
#    source: https://github.com/diddledan/snapcraft-preload.git
#    source-branch: semaphore-support
#    plugin: cmake
#    build-packages:
#      - gcc-multilib
#      - g++-multilib


apps:
  genx:
    command: bin/desktop-launch $SNAP/bin/genx
    plugs: [desktop, x11, audio-playback, desktop-legacy, unity7, network, home, gsettings, opengl]
    environment:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8

plugs:
  gnome-3-38-2004:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-38-2004
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
      
