name: genx
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - wxpython
  - matplotlib
  - platformdirs
  - h5py
  - scipy
  - psutil
  - pymysql
  - numba
  - cudatoolkit
  - vtk
  - pyinstaller
  - requests
  - pip:
    - bumps
    - orsopy
    - svgwrite
