# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: 
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat env update --file genx\windows_build\conda_build.yml --name base
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Build with pyinstaller
      run: |
        cd genx
        pyinstaller genx.spec
    - name: Download and Install Inno Setup installer
      run: |
        curl -L -o installer.exe http://files.jrsoftware.org/is/6/innosetup-6.1.2.exe
        ./installer.exe /verysilent /allusers /dir=inst
    - name: Build setup file
      run: |
        cd genx\windows_build
        python update_version.py
        iscc genx.iss
    - name: Archive distribution
      uses: actions/upload-artifact@v2
      with:
        name: windows-dist
        path: |
          genx\windows_build\Output\GenX-*_win64_setup.exe
        
  build-ubuntu-18:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3 python3-matplotlib python3-scipy alien rpm build-essential python3-setuptools
    - name: Build binary package
      run: |
        cd genx
        bash debian_build/make_deb.sh
    - name: Archive distribution
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-18-dist
        path: |
          genx/dist/*.deb

  build-ubuntu-20:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3 python3-matplotlib python3-scipy alien rpm build-essential python3-setuptools python3-pip
    - name: Build binary package
      run: |
        cd genx
        bash debian_build/make_deb.sh
    - name: Build PyPI package
      run: |
        cd genx
        pip3 install build
        python3 -m build
    - name: Move dist folder
      run: |
        mv genx/dist ./dist
        cd ..
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        skip_existing: true
    - name: Archive distribution
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-20-dist
        path: |
          dist/*.deb
          dist/*.tar.gz
          dist/*.whl

  release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu-18, build-ubuntu-20, build-windows]
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: ubuntu-18-dist
    - uses: actions/download-artifact@v2
      with:
        name: ubuntu-20-dist
    - uses: actions/download-artifact@v2
      with:
        name: windows-dist
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "genx*.deb,genx*.tar.gz,GenX-*_win64_setup.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
