# This is a basic workflow to help you get started with Actions

name: Test SF Upload

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  release-sourceforge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install sshpass
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
    - name: Upload files
      run: |
        touch test_upload.txt
        rsync --progress -urzv test_upload.txt ${{secrets.SF_USER}}@frs.sourceforge.net:/home/pfs/project/genx/
